services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: news
      POSTGRES_PASSWORD: newspass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news -d newsdb"]
      interval: 5s
      timeout: 3s
      retries: 10
